name: CI

on:
  push:
    branches:
      - main
      - release
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - main
      - release
    paths-ignore:
      - "**.md"

env:
  CHEF_LICENSE: accept-no-persist
jobs:
  ci:
   uses: codenamephp/workflows.chef/.github/workflows/ci.yml@main
   secrets: inherit